//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTMMISModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTMMIS_Entity : DbContext
    {
        public CTMMIS_Entity()
            : base("name=CTMMIS_Entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Case_Main> t_Case_Main { get; set; }
        public virtual DbSet<t_Flow_Base> t_Flow_Base { get; set; }
        public virtual DbSet<t_Flow_Trade> t_Flow_Trade { get; set; }
    }
}
