//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTMMISModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flow_Trade
    {
        public int TradeId { get; set; }
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public string TradeType { get; set; }
        public string Property { get; set; }
        public string PriceType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string GotMoneyType { get; set; }
        public Nullable<decimal> GotMoney { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> CompactDate { get; set; }
        public string ClientCommType { get; set; }
        public Nullable<decimal> ClientComm { get; set; }
        public Nullable<System.DateTime> ClientPreDate { get; set; }
        public string HostCommType { get; set; }
        public Nullable<decimal> HostComm { get; set; }
        public Nullable<System.DateTime> HostPreDate { get; set; }
        public string NonCorpIncomeType { get; set; }
        public Nullable<decimal> NonCorpIncome { get; set; }
        public string RealPayoutType { get; set; }
        public Nullable<decimal> RealPayout { get; set; }
        public string CorpIncomeType { get; set; }
        public Nullable<decimal> CorpIncome { get; set; }
        public string TaxType { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> AnJieMoney { get; set; }
        public Nullable<decimal> LawMoney { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> StateFlag { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
        public string OverType { get; set; }
        public string OverMoneyType { get; set; }
        public Nullable<decimal> OverMoney { get; set; }
        public string ChangeCause { get; set; }
        public string discountCause { get; set; }
        public string NonCorpIncomeType2 { get; set; }
        public Nullable<decimal> NonCorpIncome2 { get; set; }
        public string RealPayoutType2 { get; set; }
        public Nullable<decimal> RealPayout2 { get; set; }
        public Nullable<decimal> Tax2 { get; set; }
        public string TaxType2 { get; set; }
        public string NonCorpIncomeType3 { get; set; }
        public Nullable<decimal> NonCorpIncome3 { get; set; }
        public string RealPayoutType3 { get; set; }
        public Nullable<decimal> RealPayout3 { get; set; }
        public string TaxType3 { get; set; }
        public Nullable<decimal> Tax3 { get; set; }
        public Nullable<decimal> CooprateAmount { get; set; }
        public string CooprateType { get; set; }
        public Nullable<decimal> ZJAmount { get; set; }
        public string ZJType { get; set; }
        public string cashRule { get; set; }
        public Nullable<decimal> cashAmount { get; set; }
        public string areaDirector { get; set; }
        public string ChangeType { get; set; }
        public string PRootid { get; set; }
        public Nullable<int> IsNew { get; set; }
        public string ZPriceType { get; set; }
        public Nullable<decimal> ZPrice { get; set; }
        public Nullable<int> IsLast { get; set; }
        public Nullable<int> IsRpt { get; set; }
        public Nullable<int> IsClear { get; set; }
        public Nullable<int> IsNewHome { get; set; }
        public string ContractType { get; set; }
        public Nullable<System.DateTime> EarnestDate { get; set; }
        public Nullable<int> JuJian { get; set; }
        public string JuJianCode { get; set; }
        public string NoJuJianReason { get; set; }
        public Nullable<int> mandate { get; set; }
        public Nullable<int> ConnectFile { get; set; }
        public Nullable<int> YSHouse { get; set; }
        public Nullable<System.DateTime> ConnectDate { get; set; }
        public Nullable<System.DateTime> CertifeDate { get; set; }
        public Nullable<decimal> CommMoney { get; set; }
        public Nullable<decimal> AnJieMoneyRate { get; set; }
        public Nullable<decimal> TotalPercent { get; set; }
        public Nullable<decimal> TotalNum { get; set; }
        public Nullable<decimal> TotalComm { get; set; }
        public Nullable<decimal> TotalAchive { get; set; }
        public Nullable<decimal> TotalCommPercent { get; set; }
        public string HostCommChange { get; set; }
        public string ClientCommChange { get; set; }
        public string DiscountChange { get; set; }
        public string CommMoneyChange { get; set; }
        public string CorpIncomeChange { get; set; }
        public string AnJieMoneyChange { get; set; }
        public string AnJieMoneyRateChange { get; set; }
        public string ZYReason { get; set; }
        public Nullable<decimal> ContractPer { get; set; }
        public Nullable<decimal> PercentChange { get; set; }
        public Nullable<int> IsLock { get; set; }
    }
}
