//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTMMISModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Flow_Base
    {
        public string RootId { get; set; }
        public string WfmId { get; set; }
        public string FlowName { get; set; }
        public Nullable<System.DateTime> FlowTime { get; set; }
        public string UserName { get; set; }
        public string SerialNum { get; set; }
        public string OrgName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> FirstStepTime { get; set; }
        public Nullable<System.DateTime> AuditedTime { get; set; }
        public Nullable<System.DateTime> OutDeptTime { get; set; }
        public Nullable<System.DateTime> BalanceUseTime { get; set; }
        public Nullable<System.DateTime> CWFirstTime { get; set; }
        public Nullable<System.DateTime> CWSecondTime { get; set; }
        public Nullable<System.DateTime> FWFirstTime { get; set; }
        public Nullable<System.DateTime> FWSecondTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<System.DateTime> BalanceTime { get; set; }
        public Nullable<int> FlowFlag { get; set; }
        public Nullable<System.DateTime> recording_time { get; set; }
        public Nullable<System.DateTime> updated_time { get; set; }
        public string OrgId { get; set; }
        public string FinishUserId { get; set; }
        public string FinishUserName { get; set; }
        public string UserId { get; set; }
        public string FinishIdea { get; set; }
        public string CWFirstUserId { get; set; }
        public string CWSecondUserId { get; set; }
        public string FWFirstUserId { get; set; }
        public string FWSecondUserId { get; set; }
        public Nullable<int> FlowId { get; set; }
        public Nullable<int> NewAgencyPushFlag { get; set; }
        public Nullable<int> IsYCFlowFlag { get; set; }
        public string CurstatusName { get; set; }
        public string CurstatusID { get; set; }
        public Nullable<int> IsSpecialCase { get; set; }
        public string ProcessKey { get; set; }
        public string CreateUserName { get; set; }
    }
}
